
services:

  fish-register:
    build:
      context: ./fish-register
    restart: always
    ports:
    - "36900:36900"
    container_name: fish-register
    hostname: fish-register
    image: dayang/fish-register
    networks:
    - spring_cloud_default

  fish-gateway:
    build:
      context: ./fish-gateway
    restart: always
    ports:
    - "36901:36901"
    container_name: fish-gateway
    hostname: fish-gateway
    image: dayang/fish-gateway
    networks:
    - spring_cloud_default

  fish-job-admin:
    build:
      context: ./fish-job-admin
    restart: always
    ports:
    - "36903:36903"
    container_name: fish-job-admin
    hostname: fish-job-admin
    image: dayang/fish-job-admin
    depends_on:
    - fish-gateway
    networks:
    - spring_cloud_default

  fish-executor:
    build:
      context: ./fish-executor
    restart: always
    ports:
    - "36905:36905"
    container_name: fish-executor
    hostname: fish-executor
    image: dayang/fish-executor
    depends_on:
    - fish-gateway
    - fish-job-admin
    networks:
    - spring_cloud_default


networks:
  spring_cloud_default:
    driver: bridge
