
services:

  fish-register:
    build:
      context: ./fish-register
    restart: always
    ports:
    - "8761:8761"
    container_name: fish-register
    hostname: fish-register
    image: dayang/fish-register
    networks:
    - spring_cloud_default

  fish-gateway:
    build:
      context: ./fish-gateway
    restart: always
    ports:
    - "36901:36901"
    container_name: fish-gateway
    hostname: fish-gateway
    image: dayang/fish-gateway
    networks:
    - spring_cloud_default

  fish-job-admin:
    build:
      context: ./fish-job-admin
    restart: always
    ports:
    - "36903:36903"
    container_name: fish-job-admin
    hostname: fish-job-admin
    image: dayang/fish-job-admin
    depends_on:
    - fish-gateway
    networks:
    - spring_cloud_default

  fish-business:
    build:
      context: ./fish-business
    restart: always
    ports:
    - "36907:36907"
    container_name: fish-business
    hostname: fish-business
    image: dayang/fish-business
    networks:
    - spring_cloud_default


networks:
  spring_cloud_default:
    driver: bridge
