spring:
  datasource:
    druid:
      initial-size: 5
      max-active: 30
      min-idle: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 100000
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.18.99:5432/fish?currentSchema=public&stringtype=unspecified
          username: postgres
          password: postgres
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initial-size: 5
            validation-query: SELECT 1
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.18.99:3306/fish?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&allowMultiQueries=true
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource
        oracle:
          driver-class-name: oracle.jdbc.OracleDriver
          url: jdbc:oracle:thin:@127.0.0.1:1521/dbname
          username: oracle
          password: oracle
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initial-size: 5
            validation-query: SELECT 1 FROM DUAL
        oscar:
          driver-class-name: com.oscar.Driver
          url: jdbc:oscar://127.0.0.1:2003/osrdb
          username: SYSDBA
          password: szoscar55
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initial-size: 5
            validation-query: SELECT 1
  redis:
    host: 192.168.18.99
    port: 6379
    username:
    password:
    database: 10
    ssl: false
    timeout: 1s
    connect-timeout: 3s

logging:
  level:
    web: debug
    org.springframework.web: debug
    org.springframework.client: info
    com.netflix.eureka.registry: warn
    com.fish: info
    com.xxl.job.admin.dao: info
