spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=public&stringtype=unspecified
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      # 获取客户端等待池中连接的最大毫秒数
      connection-timeout: 3000
      # 允许连接在池中处于空闲状态的最长时间（以毫秒为单位）
      idle-timeout: 30000


  redis:
    host: 127.0.0.1
    port: 6379
    username:
    password:
    database: 1
    ssl: false
    timeout: 1s
    connect-timeout: 3s

logging:
  level:
    web: debug
    org.springframework.web: debug
    org.springframework.client: info
    com.netflix.eureka.registry: warn
    com.fish: debug
    com.xxl.job.admin.dao: debug
    com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder: error
