server:
  port: 36901

spring:
  application:
    name: ${artifactId}
  cloud:
    nacos:
      username: ${FISH_NACOS_USERNAME:nacos}
      password: ${FISH_NACOS_PASSWORD:nacos}
      server-addr: ${FISH_NACOS_IP:localhost}:${FISH_NACOS_PORT:8848}
      config:
        enabled: true
        file-extension: yaml
        namespace: ${FISH_NACOS_NAMESPACE:dev}
        group: ${FISH_NACOS_GROUP:DEFAULT_GROUP}
      discovery:
        enabled: true
        namespace: ${FISH_NACOS_NAMESPACE:dev}
        group: ${FISH_NACOS_GROUP:DEFAULT_GROUP}
        metadata:
          # 发送心跳的间隔时间，单位毫秒
          preserved.heart.beat.interval: 1000
          # 多长时间内没有收到服务实例的心跳时认为该实例不可用的超时时间，单位毫秒
          preserved.heart.beat.timeout: 3000
          # 删除不健康实例的超时时间，单位毫秒
          preserved.ip.delete.timeout: 3000
    inetutils:
      ignored-interfaces:
        - VMware.*
        - VirtualBox.*
        - veth
        - docker
        - cali
        - br
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            # 注意这个设置只对 spring boot 2.4+ 有效，低版本 使用  allowedOrigins: "*" 属性
            allowedOriginPatterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 86400
            exposedHeaders: "Content-Disposition,Content-Type,Cache-Control"
      routes:
        - id: fish-driver-user
          uri: lb://fish-driver-user
          predicates:
            - Path=/drivers/**
            - Method=GET,POST
        - id: oauth2-service-routes
          uri: lb://oauth2-service
          predicates:
            - Path=/**
          filters:
            - PrefixPath=0
    loadbalancer:
      nacos:
        enabled: true
  config:
    import:
      - optional:nacos:share-fish-config.DEFAULT_GROUP.yaml?refreshEnabled=true
      - optional:nacos:share-fish-config-${FISH_PROFILES_ACTIVE:dev}.DEFAULT_GROUP.yaml?refreshEnabled=true

eureka:
  instance:
    # 默认为电脑名
    hostname: ${FISH_EUREKA_IP:localhost}
    # 测主机名为IP形式
    prefer-ip-address: true
    # 默认值为主机名+服务名+端口
    instance-id: ${spring.application.name}:${server.port}
  client:
    enabled: false
    service-url:
      defaultZone: http://${FISH_EUREKA_IP:localhost}:${FISH_EUREKA_PORT:8761}/eureka/


logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: debug
    org.springframework.core.codec.CharSequenceEncoder: debug


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

