CREATE TABLE USER_INFO
(
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NICK_NAME     VARCHAR2(50),
    USER_ACCOUNT  VARCHAR2(50)
        CONSTRAINT "UNI_USER_ACCOUNT" UNIQUE,
    USER_PASSWORD VARCHAR2(50),
    AVATAR_URL    VARCHAR2(100),
    GENDER        CHAR(1),
    AGE           NUMBER(3, 0),
    PHONE         VARCHAR2(20),
    EMAIL         VARCHAR2(50)
        CONSTRAINT "UNI_EMAIL" UNIQUE,
    ADMIN_FLAG    NUMBER(1, 0) DEFAULT 0,
    USER_STATUS   NUMBER(1, 0) DEFAULT 0,
    PLANET_CODE   VARCHAR2(20),
    TAGS          VARCHAR2(2000),
    CREATE_TIME   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME   TIMESTAMP(0),
    DELETE_FLAG   CHAR(1)      DEFAULT 0
);


COMMENT ON COLUMN USER_INFO.ID IS '主键自增';
COMMENT ON COLUMN USER_INFO.NICK_NAME IS '昵称';
COMMENT ON COLUMN USER_INFO.USER_ACCOUNT IS '账户';
COMMENT ON COLUMN USER_INFO.USER_PASSWORD IS '密码';
COMMENT ON COLUMN USER_INFO.AVATAR_URL IS '头像链接';
COMMENT ON COLUMN USER_INFO.GENDER IS '性别：0---女，1---男';
COMMENT ON COLUMN USER_INFO.AGE IS '年龄';
COMMENT ON COLUMN USER_INFO.PHONE IS '手机号';
COMMENT ON COLUMN USER_INFO.EMAIL IS '邮箱';
COMMENT ON COLUMN USER_INFO.ADMIN_FLAG IS '0-普通用户，1-管理员';
COMMENT ON COLUMN USER_INFO.USER_STATUS IS '用户状态: 0-正常';
COMMENT ON COLUMN USER_INFO.PLANET_CODE IS '星球编号';
COMMENT ON COLUMN USER_INFO.TAGS IS '标签Json列表';
COMMENT ON COLUMN USER_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN USER_INFO.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN USER_INFO.DELETE_FLAG IS '是否逻辑删除';
COMMENT ON TABLE USER_INFO IS '用户表';
