-- XXL-JOB v2.4.1
-- Copyright (c) 2015-present, xuxueli.

-- 信息表
CREATE TABLE XXL_JOB_INFO
(
    ID                        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_GROUP                 NUMBER(10, 0) NOT NULL,
    JOB_DESC                  VARCHAR2(255) NOT NULL,
    ADD_TIME                  TIMESTAMP(0),
    UPDATE_TIME               TIMESTAMP(0),
    AUTHOR                    VARCHAR2(64),
    ALARM_EMAIL               VARCHAR2(255),
    SCHEDULE_TYPE             VARCHAR2(50)  DEFAULT 'NONE',
    SCHEDULE_CONF             VARCHAR2(128),
    MISFIRE_STRATEGY          VARCHAR2(50)  DEFAULT 'DO_NOTHING',
    EXECUTOR_ROUTE_STRATEGY   VARCHAR2(50),
    EXECUTOR_HANDLER          VARCHAR2(255),
    EXECUTOR_PARAM            VARCHAR2(512),
    EXECUTOR_BLOCK_STRATEGY   VARCHAR2(50),
    EXECUTOR_TIMEOUT          NUMBER(5, 0)  DEFAULT 0,
    EXECUTOR_FAIL_RETRY_COUNT NUMBER(5, 0)  DEFAULT 0,
    GLUE_TYPE                 VARCHAR2(50)  NOT NULL,
    GLUE_SOURCE               VARCHAR2(3000),
    GLUE_REMARK               VARCHAR2(128),
    GLUE_UPDATETIME           TIMESTAMP(3),
    CHILD_JOBID               VARCHAR2(255),
    TRIGGER_STATUS            NUMBER(5, 0)  DEFAULT 0,
    TRIGGER_LAST_TIME         NUMBER(20, 0) DEFAULT 0,
    TRIGGER_NEXT_TIME         NUMBER(20, 0) DEFAULT 0
)
;

COMMENT ON COLUMN XXL_JOB_INFO.ID IS '主键';
COMMENT ON COLUMN XXL_JOB_INFO.JOB_GROUP IS '执行器主键ID';
COMMENT ON COLUMN XXL_JOB_INFO.JOB_DESC IS '任务描述';
COMMENT ON COLUMN XXL_JOB_INFO.AUTHOR IS '作者';
COMMENT ON COLUMN XXL_JOB_INFO.ALARM_EMAIL IS '报警邮件';
COMMENT ON COLUMN XXL_JOB_INFO.SCHEDULE_TYPE IS '调度类型';
COMMENT ON COLUMN XXL_JOB_INFO.SCHEDULE_CONF IS '调度配置，值含义取决于调度类型';
COMMENT ON COLUMN XXL_JOB_INFO.MISFIRE_STRATEGY IS '调度过期策略';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_ROUTE_STRATEGY IS '执行器路由策略';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_HANDLER IS '执行器任务handler';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_PARAM IS '执行器任务参数';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_BLOCK_STRATEGY IS '阻塞处理策略';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_TIMEOUT IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_FAIL_RETRY_COUNT IS '失败重试次数';
COMMENT ON COLUMN XXL_JOB_INFO.GLUE_TYPE IS 'GLUE类型';
COMMENT ON COLUMN XXL_JOB_INFO.GLUE_SOURCE IS 'GLUE源代码';
COMMENT ON COLUMN XXL_JOB_INFO.GLUE_REMARK IS 'GLUE备注';
COMMENT ON COLUMN XXL_JOB_INFO.GLUE_UPDATETIME IS 'GLUE更新时间';
COMMENT ON COLUMN XXL_JOB_INFO.CHILD_JOBID IS '子任务ID，多个逗号分隔';
COMMENT ON COLUMN XXL_JOB_INFO.TRIGGER_STATUS IS '调度状态：0-停止，1-运行';
COMMENT ON COLUMN XXL_JOB_INFO.TRIGGER_LAST_TIME IS '上次调度时间';
COMMENT ON COLUMN XXL_JOB_INFO.TRIGGER_NEXT_TIME IS '下次调度时间';

COMMENT ON TABLE XXL_JOB_INFO IS '存储任务调度信息的表';

-- 日志表
CREATE TABLE XXL_JOB_LOG
(
    ID                        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_GROUP                 NUMBER(10, 0) NOT NULL,
    JOB_ID                    NUMBER(10, 0) NOT NULL,
    EXECUTOR_ADDRESS          VARCHAR2(255),
    EXECUTOR_HANDLER          VARCHAR2(255),
    EXECUTOR_PARAM            VARCHAR2(512),
    EXECUTOR_SHARDING_PARAM   VARCHAR2(20),
    EXECUTOR_FAIL_RETRY_COUNT NUMBER(10, 0) DEFAULT 0,
    TRIGGER_TIME              TIMESTAMP(3),
    TRIGGER_CODE              NUMBER(10, 0) NOT NULL,
    TRIGGER_MSG               VARCHAR2(3000),
    HANDLE_TIME               TIMESTAMP(3),
    HANDLE_CODE               NUMBER(10, 0) NOT NULL,
    HANDLE_MSG                VARCHAR2(3000),
    ALARM_STATUS              NUMBER(5, 0)  DEFAULT 0

)
;

COMMENT ON COLUMN XXL_JOB_LOG.ID IS '主键';
COMMENT ON COLUMN XXL_JOB_LOG.JOB_GROUP IS '执行器主键ID';
COMMENT ON COLUMN XXL_JOB_LOG.JOB_ID IS '任务，主键ID';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_ADDRESS IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_HANDLER IS '执行器任务handler';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_PARAM IS '执行器任务参数';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_SHARDING_PARAM IS '执行器任务分片参数，格式如 1/2';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_FAIL_RETRY_COUNT IS '失败重试次数';
COMMENT ON COLUMN XXL_JOB_LOG.TRIGGER_TIME IS '调度-时间';
COMMENT ON COLUMN XXL_JOB_LOG.TRIGGER_CODE IS '调度-结果';
COMMENT ON COLUMN XXL_JOB_LOG.TRIGGER_MSG IS '调度-日志';
COMMENT ON COLUMN XXL_JOB_LOG.HANDLE_TIME IS '执行-时间';
COMMENT ON COLUMN XXL_JOB_LOG.HANDLE_CODE IS '执行-状态';
COMMENT ON COLUMN XXL_JOB_LOG.HANDLE_MSG IS '执行-日志';
COMMENT ON COLUMN XXL_JOB_LOG.ALARM_STATUS IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';

COMMENT ON TABLE XXL_JOB_LOG IS '存储任务执行日志的表';

CREATE INDEX IDX_HANDLE_CODE
    ON XXL_JOB_LOG (HANDLE_CODE);
CREATE INDEX IDX_TRIGGER_TIME
    ON XXL_JOB_LOG (TRIGGER_TIME);


-- xxl_job_log_report
CREATE TABLE XXL_JOB_LOG_REPORT
(
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRIGGER_DAY   TIMESTAMP(3),
    RUNNING_COUNT NUMBER(5, 0) default 0,
    SUC_COUNT     NUMBER(5, 0) default 0,
    FAIL_COUNT    NUMBER(5, 0) default 0,
    UPDATE_TIME   TIMESTAMP(3),
    constraint UNI_TRIGGER_DAY unique (TRIGGER_DAY)

)
;

COMMENT ON COLUMN XXL_JOB_LOG_REPORT.ID IS '主键';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.TRIGGER_DAY IS '调度-时间';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.RUNNING_COUNT IS '运行中-日志数量';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.SUC_COUNT IS '执行成功-日志数量';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.FAIL_COUNT IS '执行失败-日志数量';
COMMENT ON TABLE XXL_JOB_LOG_REPORT IS '调度任务执行日志表';


-- xxl_job_logglue
CREATE TABLE XXL_JOB_LOGGLUE
(
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_ID      NUMBER(10, 0) NOT NULL,
    GLUE_TYPE   VARCHAR2(50),
    GLUE_SOURCE VARCHAR2(3000),
    GLUE_REMARK VARCHAR2(128) NOT NULL,
    ADD_TIME    TIMESTAMP(3),
    UPDATE_TIME TIMESTAMP(3)
)
;

COMMENT ON COLUMN XXL_JOB_LOGGLUE.ID IS '主键';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.JOB_ID IS '任务，主键ID';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.GLUE_TYPE IS 'GLUE类型';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.GLUE_SOURCE IS 'GLUE源代码';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.GLUE_REMARK IS 'GLUE备注';
COMMENT ON TABLE XXL_JOB_LOGGLUE IS 'XXL-JOB 调度任务 GLUE 代码表';


-- xxl_job_registry
CREATE TABLE XXL_JOB_REGISTRY
(
    ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REGISTRY_GROUP VARCHAR2(50)  NOT NULL,
    REGISTRY_KEY   VARCHAR2(255) NOT NULL,
    REGISTRY_VALUE VARCHAR2(255) NOT NULL,
    UPDATE_TIME    TIMESTAMP(0)
)
;

CREATE INDEX idx_g_k_v
    on xxl_job_registry (registry_group, registry_key, registry_value);

COMMENT ON COLUMN XXL_JOB_REGISTRY.ID IS '自增ID';
COMMENT ON COLUMN XXL_JOB_REGISTRY.REGISTRY_GROUP IS '注册分组';
COMMENT ON COLUMN XXL_JOB_REGISTRY.REGISTRY_KEY IS '注册键';
COMMENT ON COLUMN XXL_JOB_REGISTRY.REGISTRY_VALUE IS '注册值';
COMMENT ON COLUMN XXL_JOB_REGISTRY.UPDATE_TIME IS '更新时间';
COMMENT ON TABLE XXL_JOB_REGISTRY IS 'XXL-JOB 执行器注册信息表';

-- xxl_job_group
CREATE TABLE XXL_JOB_GROUP
(
    ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP_NAME     VARCHAR2(64) NOT NULL,
    TITLE        VARCHAR2(30) NOT NULL,
    ADDRESS_TYPE NUMBER(5, 0) DEFAULT 0,
    ADDRESS_LIST VARCHAR2(3000),
    UPDATE_TIME  TIMESTAMP(0)
)
;

COMMENT ON COLUMN XXL_JOB_GROUP.ID IS '主键';
COMMENT ON COLUMN XXL_JOB_GROUP.APP_NAME IS '执行器AppName';
COMMENT ON COLUMN XXL_JOB_GROUP.TITLE IS '执行器名称';
COMMENT ON COLUMN XXL_JOB_GROUP.ADDRESS_TYPE IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN XXL_JOB_GROUP.ADDRESS_LIST IS '执行器地址列表，多地址逗号分隔';
COMMENT ON TABLE XXL_JOB_GROUP IS 'XXL-JOB 执行器注册信息表';

-- xxl_job_lock
CREATE TABLE XXL_JOB_LOCK
(
    LOCK_NAME VARCHAR2(50) NOT NULL PRIMARY KEY
);

COMMENT ON COLUMN XXL_JOB_LOCK.LOCK_NAME IS '锁名称';
COMMENT ON TABLE XXL_JOB_LOCK IS '分布式锁表';


-- xxl_job_user
CREATE TABLE XXL_JOB_USER
(
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME   VARCHAR2(50)  NOT NULL,
    PASSWORD   VARCHAR2(50)  NOT NULL,
    ROLE       NUMBER(5, 0)  NOT NULL,
    PERMISSION VARCHAR2(255) null,
    CONSTRAINT UNI_USERNAME UNIQUE (USERNAME)

)
;

COMMENT ON COLUMN XXL_JOB_USER.USERNAME IS '账号';
COMMENT ON COLUMN XXL_JOB_USER.PASSWORD IS '密码';
COMMENT ON COLUMN XXL_JOB_USER.ROLE IS '角色：0-普通用户、1-管理员';
COMMENT ON COLUMN XXL_JOB_USER.PERMISSION IS '权限：执行器ID列表，多个逗号分割';
COMMENT ON TABLE XXL_JOB_USER IS 'XXL-JOB 用户信息表';

-- 插入初始化语句
insert into XXL_JOB_GROUP(APP_NAME, TITLE, ADDRESS_TYPE, ADDRESS_LIST, UPDATE_TIME)
values ('default-executor', '默认执行器', 0, null, TO_DATE('2023-09-26 12:52:31', 'YYYY-MM-DD HH24:MI:SS'));

insert into XXL_JOB_INFO(JOB_GROUP, JOB_DESC, ADD_TIME, UPDATE_TIME, AUTHOR, ALARM_EMAIL, SCHEDULE_TYPE,
                         SCHEDULE_CONF, MISFIRE_STRATEGY, EXECUTOR_ROUTE_STRATEGY, EXECUTOR_HANDLER, EXECUTOR_PARAM,
                         EXECUTOR_BLOCK_STRATEGY, EXECUTOR_TIMEOUT, EXECUTOR_FAIL_RETRY_COUNT, GLUE_TYPE, GLUE_SOURCE,
                         GLUE_REMARK, GLUE_UPDATETIME, CHILD_JOBID)
values (1, '测试任务1', TO_DATE('2018-11-03 22:21:31', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2018-11-03 22:21:31', 'YYYY-MM-DD HH24:MI:SS'), 'XXL', '', 'CRON', '0 0 0 * * ? *',
        'DO_NOTHING', 'FIRST', 'demoJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        TO_DATE('2018-11-03 22:21:31', 'YYYY-MM-DD HH24:MI:SS'), '');

insert into XXL_JOB_USER(USERNAME, PASSWORD, ROLE, PERMISSION)
values ('admin', 'e10adc3949ba59abbe56e057f20f883e', 1, null);

insert into XXL_JOB_LOCK (LOCK_NAME)
values ('schedule_lock');
