server:
  port: 36907

spring:
  application:
    name: ${artifactId}
  rabbitmq:
    host: dayang.com
    port: 5672
    username: admin
    password: admin
    ssl:
      enabled: false
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1GB
  cloud:
    nacos:
      username: ${FISH_NACOS_USERNAME:nacos}
      password: ${FISH_NACOS_PASSWORD:nacos}
      server-addr: ${FISH_NACOS_IP:localhost}:${FISH_NACOS_PORT:8848}
      config:
        enabled: true
        file-extension: yaml
        namespace: ${FISH_NACOS_NAMESPACE:dev}
        group: ${FISH_NACOS_GROUP:DEFAULT_GROUP}
      discovery:
        enabled: true
        namespace: ${FISH_NACOS_NAMESPACE:dev}
        group: ${FISH_NACOS_GROUP:DEFAULT_GROUP}
    inetutils:
      ignored-interfaces:
        - VMware.*
        - VirtualBox.*
  config:
    import:
    - optional:nacos:share-fish-config.yaml?refreshEnabled=true
    - optional:nacos:share-fish-config-${FISH_PROFILES_ACTIVE:dev}.yaml?refreshEnabled=true

eureka:
  instance:
    # 默认为电脑名
    hostname: ${FISH_EUREKA_IP:localhost}
    # 测主机名为IP形式
    prefer-ip-address: true
    # 默认值为主机名+服务名+端口
    instance-id: ${spring.application.name}:${server.port}
  client:
    enabled: false
    service-url:
      defaultZone: http://${FISH_EUREKA_IP:localhost}:${FISH_EUREKA_PORT:8761}/eureka/

xxljob:
  appname: default-executor
  port: 9898

monitor:
  file-path: D:/temp

rocketmq:
  name-server: "localhost:8888"

knife4j:
  enable: true
  setting:
    language: zh_cn

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
minio:
  endpoint: http://192.168.18.99:9000
  access-key: dayang
  secret-key: 123456789
