version: '3.8'

services:
  adguard:
    image: adguard/adguardhome:v0.107.43
    restart: always
    privileged: true
    container_name: adguardhome
    ports:
    - "53:53"
    - "3000:3000"
    volumes:
    - ./workData:/opt/adguardhome/work
    - ./confData:/opt/adguardhome/conf
    environment:
    - TZ=Asia/Shanghai
