services:

  gitea:
    image: gitea/gitea:1.22.0
    container_name: gitea
    privileged: true
    restart: always
    environment:
    - APP_NAME="Code changes the world"
    - USER_UID=1000
    - USER_GID=1000
    - SSH_PORT=222
    - SSH_LISTEN_PORT=22
    volumes:
    - ./giteaData:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    ports:
    - "3000:3000"
    - "222:22"
