services:

  minio:
    image: bitnami/minio:2024.1.18
    restart: always
    privileged: true
    container_name: minio
    ports:
    - "9000:9000"
    - "9001:9001"
    volumes:
    - ./miniodata:/bitnami/minio/data
    environment:
    - TZ=Asia/Shanghai
    - MINIO_ROOT_USER=dayang
    - MINIO_ROOT_PASSWORD=123456789
