version: '3.8'

services:
  nacos:
    image: nacos/nacos-server:v2.2.3-slim
    restart: always
    privileged: true
    container_name: nacos
    ports:
    - "8848:8848"
    - "9848:9848"
    - "9849:9849"
    volumes:
    - ./nacosData:/home/nacos/data
    - ./logs:/home/nacos/logs
    environment:
    - MODE=standalone
    - NACOS_AUTH_ENABLE=true
    - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    - NACOS_AUTH_TOKEN_EXPIRE_SECONDS=1800000
    - NACOS_AUTH_CACHE_ENABLE=true
    - NACOS_AUTH_IDENTITY_KEY=serverIdentity
    - NACOS_AUTH_IDENTITY_VALUE=security
    - TZ=Asia/Shanghai
