version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12.12-management
    restart: always
    privileged: true
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
    - TZ=Asia/Shanghai
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=123456
