
services:

  rabbitmq:
    image: rabbitmq:4.0-management
    restart: always
    privileged: true
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
    - ./rabbitmqData:/var/lib/rabbitmq
    environment:
    - TZ=Asia/Shanghai
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
