version: '3.8'

services:
  nacos:
    image: nacos/nacos-server:v2.3.2-slim
    restart: always
    privileged: true
    container_name: nacos
    ports:
    - "7848:7848"
    - "8848:8848"
    - "9848:9848"
    - "9849:9849"
    volumes:
    - ./nacosData:/home/nacos/data
    - ./logs:/home/nacos/logs
    environment:
    - MODE=standalone
    - NACOS_SERVER_PORT=8848
    - NACOS_AUTH_ENABLE=true
    - JVM_XMS=1g
    - JVM_XMX=1g
    - JVM_XMN=512m
    - JVM_MS=128m
    - JVM_MMS=320m
    - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    - NACOS_AUTH_TOKEN_EXPIRE_SECONDS=1800000
    - NACOS_AUTH_CACHE_ENABLE=true
    - NACOS_AUTH_IDENTITY_KEY=serverIdentity
    - NACOS_AUTH_IDENTITY_VALUE=security
    - NACOS_INETUTILS_IGNORED_INTERFACES[0]=VMware.*
    - NACOS_INETUTILS_IGNORED_INTERFACES[1]=br-.*
    - NACOS_INETUTILS_IGNORED_INTERFACES[2]=docker.*
    - NACOS_INETUTILS_IGNORED_INTERFACES[3]=veth.*
    - TZ=Asia/Shanghai
