version: '3.8'

services:

  nginx:
    image: nginx:1.24.0
    restart: unless-stopped
    hostname: nginx
    container_name: nginx
    privileged: true
    ports:
    - "880:80"
    - "8443:443"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/logs/:/var/log/nginx/
    - ./nginx/cert/:/etc/nginx/cert/:ro
    - ./html:/usr/share/nginx/html
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
# docker run --name tmp-nginx-container -d nginx:1.24.0
# docker cp tmp-nginx-container:/etc/nginx/nginx.conf /docker/nginx/nginx.conf
# docker rm -f tmp-nginx-container