server:
  port: 36909

spring:
  application:
    name: ${artifactId}
  profiles:
    active: local
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "Asia/Shanghai"
    serialization:
      write-dates-as-timestamps: true
  mvc:
    log-request-details: true
  freemarker:
    check-template-location: false
  session:
    timeout: 86400
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dayang.com:5432/postgres?currentSchema=public&stringtype=unspecified
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      # 获取客户端等待池中连接的最大毫秒数
      connection-timeout: 3000
      # 允许连接在池中处于空闲状态的最长时间（以毫秒为单位）
      idle-timeout: 30000


  data:
    redis:
      host: dayang.com
      port: 6379
      password: 123456
      database: 1
      timeout: 1s
      connect-timeout: 3s


  cloud:
    nacos:
      username: ${FISH_NACOS_USERNAME:nacos}
      password: ${FISH_NACOS_PASSWORD:nacos}
      server-addr: ${FISH_NACOS_IP:localhost}:${FISH_NACOS_PORT:8848}
      config:
        enabled: false
        file-extension: yaml
        namespace: ${FISH_NACOS_NAMESPACE:dev}
        group: ${FISH_NACOS_GROUP:DEFAULT_GROUP}
      discovery:
        enabled: false
        namespace: ${FISH_NACOS_NAMESPACE:dev}
        group: ${FISH_NACOS_GROUP:DEFAULT_GROUP}
    inetutils:
      ignored-interfaces:
        - VMware.*
        - VirtualBox.*
  config:
    import:
    - optional:nacos:share-fish-config.yaml?refreshEnabled=true
    - optional:nacos:share-fish-config-${FISH_PROFILES_ACTIVE:dev}.yaml?refreshEnabled=true


mybatis:
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    variables:
      fish: fish
  type-handlers-package: "com.fish.user.config.type"
  type-aliases-package: "com.fish.user.entity"

mybatis-plus:
  mapper-locations: "classpath*:/mapper/**/*.xml"
  type-aliases-package: "com.fish.user.entity"
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    variables:
      fish: fish
  global-config:
    db-config:
      logic-delete-field: del_flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


logging:
  level:
    web: info
    org.springframework.web: info
    com.netflix.eureka.registry: info
    com.fish.user: debug
  file:
    name: ./logs/${spring.application.name}/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 30
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log.gz"
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
  charset:
    console: UTF-8
    file: UTF-8


eureka:
  instance:
    # 默认为电脑名
    hostname: ${FISH_EUREKA_IP:localhost}
    # 测主机名为IP形式
    prefer-ip-address: true
    # 默认值为主机名+服务名+端口
    instance-id: ${spring.application.name}:${server.port}
  client:
    enabled: false
    service-url:
      defaultZone: http://${FISH_EUREKA_IP:localhost}:${FISH_EUREKA_PORT:8761}/eureka/

pagehelper:
  helper-dialect: postgresql
  reasonable: true
  defaultCount: true
  auto-runtime-dialect: true
  support-methods-arguments: true
