server:
  port: 36911
spring:
  application:
    name: ${artifactId}
  config:
    import:
    - optional:nacos:share-fish-config.yaml?refreshEnabled=true
    - optional:nacos:share-fish-config-${FISH_PROFILES_ACTIVE:dev}.yaml?refreshEnabled=true
  cloud:
    nacos:
      username: ${FISH_NACOS_USERNAME:nacos}
      password: ${FISH_NACOS_PASSWORD:nacos}
      server-addr: ${FISH_NACOS_IP:localhost}:${FISH_NACOS_PORT:8848}
      config:
        enabled: true
        file-extension: yaml
        namespace: ${FISH_NACOS_NAMESPACE:dev}
        group: ${FISH_NACOS_GROUP:DEFAULT_GROUP}
      discovery:
        enabled: true
        namespace: ${FISH_NACOS_NAMESPACE:dev}
        group: ${FISH_NACOS_GROUP:DEFAULT_GROUP}

flowable:
  async-executor-activate: true
  database-schema-update: true



logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"